In [45]:
import pandas as pd
import numpy as np

In [46]:
ds=pd.read_csv("Data1.csv")
ds

Country   Age   Salary Purchased
0       India  34.0  92000.0       yes
1   Sri lanka  22.0  25000.0       yes
2       China  31.0  74000.0       yes
3   Sri lanka  29.0      NaN        no
4       China  55.0  98000.0       yes
5       India  24.0  30000.0        no
6   Sri lanka  28.0  40000.0        no
7       India   NaN  60000.0        no
8       China  51.0  89000.0        no
9       India  44.0  78000.0       yes
10  Sri lanka  21.0  20000.0       yes
11      China  25.0  30000.0        no
12      India  33.0  45000.0       yes
13      India  42.0  65000.0       yes
14  Sri lanka  33.0  22000.0        no

In [48]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    15 non-null     object 
 1   Age        14 non-null     float64
 2   Salary     14 non-null     float64
 3   Purchased  15 non-null     object 
dtypes: float64(2), object(2)
memory usage: 608.0+ bytes


In [49]:
x=ds.iloc[:,0:-1].values
x

array([['India', 34.0, 92000.0],
       ['Sri lanka', 22.0, 25000.0],
       ['China', 31.0, 74000.0],
       ['Sri lanka', 29.0, nan],
       ['China', 55.0, 98000.0],
       ['India', 24.0, 30000.0],
       ['Sri lanka', 28.0, 40000.0],
       ['India', nan, 60000.0],
       ['China', 51.0, 89000.0],
       ['India', 44.0, 78000.0],
       ['Sri lanka', 21.0, 20000.0],
       ['China', 25.0, 30000.0],
       ['India', 33.0, 45000.0],
       ['India', 42.0, 65000.0],
       ['Sri lanka', 33.0, 22000.0]], dtype=object)

In [50]:
y=ds.iloc[:,-1].values
y

array(['yes', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'no', 'yes',
       'yes', 'no', 'yes', 'yes', 'no'], dtype=object)

In [51]:
#filling in the missing values into the data by using the SimpleImputer and using the strategy is 'mean'
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer=imputer.fit(ds[['Age','Salary']])
ds[['Age','Salary']]=imputer.transform(ds[['Age','Salary']])
ds

Country        Age        Salary Purchased
0       India  34.000000  92000.000000       yes
1   Sri lanka  22.000000  25000.000000       yes
2       China  31.000000  74000.000000       yes
3   Sri lanka  29.000000  54857.142857        no
4       China  55.000000  98000.000000       yes
5       India  24.000000  30000.000000        no
6   Sri lanka  28.000000  40000.000000        no
7       India  33.714286  60000.000000        no
8       China  51.000000  89000.000000        no
9       India  44.000000  78000.000000       yes
10  Sri lanka  21.000000  20000.000000       yes
11      China  25.000000  30000.000000        no
12      India  33.000000  45000.000000       yes
13      India  42.000000  65000.000000       yes
14  Sri lanka  33.000000  22000.000000        no

In [52]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    15 non-null     object 
 1   Age        15 non-null     float64
 2   Salary     15 non-null     float64
 3   Purchased  15 non-null     object 
dtypes: float64(2), object(2)
memory usage: 608.0+ bytes


In [53]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,0]=le.fit_transform(x[:,0])
x

array([[1, 34.0, 92000.0],
       [2, 22.0, 25000.0],
       [0, 31.0, 74000.0],
       [2, 29.0, nan],
       [0, 55.0, 98000.0],
       [1, 24.0, 30000.0],
       [2, 28.0, 40000.0],
       [1, nan, 60000.0],
       [0, 51.0, 89000.0],
       [1, 44.0, 78000.0],
       [2, 21.0, 20000.0],
       [0, 25.0, 30000.0],
       [1, 33.0, 45000.0],
       [1, 42.0, 65000.0],
       [2, 33.0, 22000.0]], dtype=object)

In [54]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y[:]=le.fit_transform(y[:])
y

array([1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0], dtype=object)

In [55]:
from sklearn.preprocessing import OneHotEncoder
dummy=pd.get_dummies(ds['Country'])
dummy

China  India  Sri lanka
0       0      1          0
1       0      0          1
2       1      0          0
3       0      0          1
4       1      0          0
5       0      1          0
6       0      0          1
7       0      1          0
8       1      0          0
9       0      1          0
10      0      0          1
11      1      0          0
12      0      1          0
13      0      1          0
14      0      0          1

In [56]:
from sklearn.preprocessing import OneHotEncoder
onehot=OneHotEncoder()
onehot.fit_transform(ds.Country.values.reshape(-1,1)).toarray()

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=0)
x_train

array([[0, 55.0, 98000.0],
       [0, 31.0, 74000.0],
       [1, 42.0, 65000.0],
       [2, 21.0, 20000.0],
       [1, nan, 60000.0],
       [0, 25.0, 30000.0],
       [2, 29.0, nan],
       [1, 34.0, 92000.0],
       [1, 24.0, 30000.0],
       [1, 33.0, 45000.0]], dtype=object)

In [59]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_train

array([[-1.28571429,  2.26630881,  1.5530053 ],
       [-1.28571429, -0.16912752,  0.64145871],
       [ 0.14285714,  0.94711413,  0.29962874],
       [ 1.57142857, -1.18389266, -1.40952112],
       [ 0.14285714,         nan,  0.1097232 ],
       [-1.28571429, -0.77798661, -1.02971004],
       [ 1.57142857, -0.37208055,         nan],
       [ 0.14285714,  0.13530202,  1.32511865],
       [ 0.14285714, -0.87946312, -1.02971004],
       [ 0.14285714,  0.0338255 , -0.45999342]])

In [60]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_test=sc.fit_transform(x_train)
x_test

array([[-1.28571429,  2.26630881,  1.5530053 ],
       [-1.28571429, -0.16912752,  0.64145871],
       [ 0.14285714,  0.94711413,  0.29962874],
       [ 1.57142857, -1.18389266, -1.40952112],
       [ 0.14285714,         nan,  0.1097232 ],
       [-1.28571429, -0.77798661, -1.02971004],
       [ 1.57142857, -0.37208055,         nan],
       [ 0.14285714,  0.13530202,  1.32511865],
       [ 0.14285714, -0.87946312, -1.02971004],
       [ 0.14285714,  0.0338255 , -0.45999342]])