In [50]:
import pandas as pd
import numpy as np

In [51]:
ds=pd.read_csv("data2.csv")
ds

Unnamed: 0  Country   Age   Salary  Purchased
0           0   France  44.0  72000.0          0
1           1    Spain  27.0  48000.0          1
2           2  Germany  30.0  54000.0          0
3           3    Spain  38.0  61000.0          0
4           4  Germany  40.0      NaN          1
5           5   France  35.0  58000.0          1
6           6    Spain   NaN  52000.0          0
7           7   France  48.0  79000.0          1
8           8  Germany  50.0  83000.0          0
9           9   France  37.0  67000.0          1

In [52]:
ds.info

<bound method DataFrame.info of    Unnamed: 0  Country   Age   Salary  Purchased
0           0   France  44.0  72000.0          0
1           1    Spain  27.0  48000.0          1
2           2  Germany  30.0  54000.0          0
3           3    Spain  38.0  61000.0          0
4           4  Germany  40.0      NaN          1
5           5   France  35.0  58000.0          1
6           6    Spain   NaN  52000.0          0
7           7   France  48.0  79000.0          1
8           8  Germany  50.0  83000.0          0
9           9   France  37.0  67000.0          1>

In [53]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  10 non-null     int64  
 1   Country     10 non-null     object 
 2   Age         9 non-null      float64
 3   Salary      9 non-null      float64
 4   Purchased   10 non-null     int64  
dtypes: float64(2), int64(2), object(1)
memory usage: 528.0+ bytes


In [54]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer=imputer.fit(ds[['Age','Salary']])
ds[['Age','Salary']]=imputer.transform(ds[['Age','Salary']])
ds

Unnamed: 0  Country        Age        Salary  Purchased
0           0   France  44.000000  72000.000000          0
1           1    Spain  27.000000  48000.000000          1
2           2  Germany  30.000000  54000.000000          0
3           3    Spain  38.000000  61000.000000          0
4           4  Germany  40.000000  63777.777778          1
5           5   France  35.000000  58000.000000          1
6           6    Spain  38.777778  52000.000000          0
7           7   France  48.000000  79000.000000          1
8           8  Germany  50.000000  83000.000000          0
9           9   France  37.000000  67000.000000          1

In [55]:
ds

Unnamed: 0  Country        Age        Salary  Purchased
0           0   France  44.000000  72000.000000          0
1           1    Spain  27.000000  48000.000000          1
2           2  Germany  30.000000  54000.000000          0
3           3    Spain  38.000000  61000.000000          0
4           4  Germany  40.000000  63777.777778          1
5           5   France  35.000000  58000.000000          1
6           6    Spain  38.777778  52000.000000          0
7           7   France  48.000000  79000.000000          1
8           8  Germany  50.000000  83000.000000          0
9           9   France  37.000000  67000.000000          1

In [56]:
x=ds.iloc[:,1:4].values
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [57]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,0]=le.fit_transform(x[:,0])
x


array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [58]:
from sklearn.preprocessing import OneHotEncoder
dummy=pd.get_dummies(ds['Country'])
dummy

France  Germany  Spain
0       1        0      0
1       0        0      1
2       0        1      0
3       0        0      1
4       0        1      0
5       1        0      0
6       0        0      1
7       1        0      0
8       0        1      0
9       1        0      0

In [59]:
from sklearn.preprocessing import OneHotEncoder
onehot=OneHotEncoder()
onehot.fit_transform(ds.Country.values.reshape(-1,1)).toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [60]:
y=ds.iloc[:,4].values
y


array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

In [76]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
x_test

array([[1, 30.0, 54000.0],
       [1, 50.0, 83000.0]], dtype=object)

In [77]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_train

array([[ 0.13483997,  0.26306757,  0.12381479],
       [-0.94387981, -0.25350148,  0.46175632],
       [ 1.21355975, -1.97539832, -1.53093341],
       [ 1.21355975,  0.05261351, -1.11141978],
       [-0.94387981,  1.64058505,  1.7202972 ],
       [ 1.21355975, -0.0813118 , -0.16751412],
       [-0.94387981,  0.95182631,  0.98614835],
       [-0.94387981, -0.59788085, -0.48214934]])

In [78]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_test=sc.fit_transform(x_test)
x_test

array([[ 0., -1., -1.],
       [ 0.,  1.,  1.]])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    15 non-null     object 
 1   Age        14 non-null     float64
 2   Salary     14 non-null     float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 608.0+ bytes


In [42]:
x=ds1.iloc[:,0:3].values
x

array([['India', 34.0, 92000.0],
       ['Sri lanka', 22.0, 25000.0],
       ['China', 31.0, 74000.0],
       ['Sri lanka', 29.0, nan],
       ['China', 55.0, 98000.0],
       ['India', 24.0, 30000.0],
       ['Sri lanka', 28.0, 40000.0],
       ['India', nan, 60000.0],
       ['China', 51.0, 89000.0],
       ['India', 44.0, 78000.0],
       ['Sri lanka', 21.0, 20000.0],
       ['China', 25.0, 30000.0],
       ['India', 33.0, 45000.0],
       ['India', 42.0, 65000.0],
       ['Sri lanka', 33.0, 22000.0]], dtype=object)

In [47]:
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
x[:,0]=le1.fit_transform(x[:,0])
x

array([[1, 34.0, 92000.0],
       [2, 22.0, 25000.0],
       [0, 31.0, 74000.0],
       [2, 29.0, nan],
       [0, 55.0, 98000.0],
       [1, 24.0, 30000.0],
       [2, 28.0, 40000.0],
       [1, nan, 60000.0],
       [0, 51.0, 89000.0],
       [1, 44.0, 78000.0],
       [2, 21.0, 20000.0],
       [0, 25.0, 30000.0],
       [1, 33.0, 45000.0],
       [1, 42.0, 65000.0],
       [2, 33.0, 22000.0]], dtype=object)

In [1]:
from sklearn.preprocessing  import OneHotEncoder
onehot=OneHotEncoder()
onehot.fit_transform(ds1.Country.values.reshape(-1,1)).toarray()


NameError: name 'ds1' is not defined

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
x_train

In [58]:
ds1=pd.read_csv("Data1.csv")
ds1

Country   Age   Salary Purchased
0       India  34.0  92000.0       Yes
1   Sri lanka  22.0  25000.0       Yes
2       China  31.0  74000.0       Yes
3   Sri lanka  29.0      NaN        No
4       China  55.0  98000.0       Yes
5       India  24.0  30000.0        No
6   Sri lanka  28.0  40000.0        No
7       India   NaN  60000.0        No
8       China  51.0  89000.0        NO
9       India  44.0  78000.0       Yes
10  Sri lanka  21.0  20000.0       Yes
11      China  25.0  30000.0       Yes
12      India  33.0  45000.0       Yes
13      India  42.0  65000.0        No
14  Sri lanka  33.0  22000.0        No

In [73]:
y=ds1.iloc[:,-1].values
y

array(['Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'NO', 'Yes',
       'Yes', 'Yes', 'Yes', 'No', 'No'], dtype=object)

In [77]:
y=ds1.iloc[:,3].values
y

array(['Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'NO', 'Yes',
       'Yes', 'Yes', 'Yes', 'No', 'No'], dtype=object)

In [81]:
from sklearn.preprocessing import LabelEncoder
le2=LabelEncoder()
y=le1.fit_transform(y)
y

array([2, 2, 2, 1, 2, 1, 1, 1, 0, 2, 2, 2, 2, 1, 1], dtype=int64)

# from sklearn.preprocessing import LabelEncoder
le2=LabelEncoder()
y[:,0]=le2.fit_transform(y[:,0])
ds1

In [53]:
ds1

Country   Age   Salary Purchased
0       India  34.0  92000.0       Yes
1   Sri lanka  22.0  25000.0       Yes
2       China  31.0  74000.0       NaN
3   Sri lanka  29.0      NaN        No
4       China  55.0  98000.0       Yes
5       India  24.0  30000.0        No
6   Sri lanka  28.0  40000.0       NaN
7       India   NaN  60000.0        No
8       China  51.0  89000.0       NaN
9       India  44.0  78000.0       Yes
10  Sri lanka  21.0  20000.0       NaN
11      China  25.0  30000.0       Yes
12      India  33.0  45000.0       Yes
13      India  42.0  65000.0       NaN
14  Sri lanka  33.0  22000.0        No